//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
  
    ViewBag.Title = "Create";


#line default
#line hidden

#line 3 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
using (Html.BeginForm()) 
{
    

#line default
#line hidden

#line 4 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.LabelFor(model => model.Current, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
               __o = Html.EditorFor(model => model.Current);


#line default
#line hidden

#line 9 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
               __o = Html.ValidationMessageFor(model => model.Current, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.LabelFor(model => model.StreetType, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.EditorFor(model => model.StreetType, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 12 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.StreetType, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 15 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" });


#line default
#line hidden

#line 16 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.LabelFor(model => model.PropertyType, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 17 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.EditorFor(model => model.PropertyType, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 18 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.PropertyType, "", new { @class = "text-danger" });


#line default
#line hidden

#line 19 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.LabelFor(model => model.Neighborhood, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 20 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.EditorFor(model => model.Neighborhood, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 21 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.Neighborhood, "", new { @class = "text-danger" });


#line default
#line hidden

#line 22 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.LabelFor(model => model.Observations, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 23 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.EditorFor(model => model.Observations, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 24 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.Observations, "", new { @class = "text-danger" });


#line default
#line hidden

#line 25 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.LabelFor(model => model.Id_City);


#line default
#line hidden

#line 26 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.DropDownListFor(model => model.Id_City, new SelectList(Model.CityList, "Id", "Name"), new { @class = "form-control chosen-select-single", @id = "selCity", data_placeholder = "-- Seleccione el municipio --" });


#line default
#line hidden

#line 27 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.Id_City, "", new { @class = "text-danger" });


#line default
#line hidden

#line 28 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.LabelFor(model => model.Id_Person);


#line default
#line hidden

#line 29 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.DropDownListFor(model => model.Id_Person, new SelectList(Model.PersonList, "Id", "FirstName"), new { @class = "form-control chosen-select-single", @id = "selPerson", data_placeholder = "-- Seleccione la persona --" });


#line default
#line hidden

#line 30 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.Id_Person, "", new { @class = "text-danger" });


#line default
#line hidden

#line 31 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
          
}

#line default
#line hidden

#line 32 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
DefineSection("Scripts", () => {


#line 33 "C:\Users\Yenny Maria\AppData\Local\Temp\EA63EC1E9EE3110D6CAE3E2E44DB90D6C7F1\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Address\Create.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
