//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageDelivery.Repository.Implementation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direccion()
        {
            this.Envio = new HashSet<Envio>();
        }
    
        public long Id { get; set; }
        public bool Actual { get; set; }
        public string TipoCalle { get; set; }
        public string Numero { get; set; }
        public string TipoInmueble { get; set; }
        public string Barrio { get; set; }
        public string Observaciones { get; set; }
        public long Id_Persona { get; set; }
        public long Id_Municipio { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envio> Envio { get; set; }
    }
}
