//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageDelivery.Repository.Implementation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public long Id { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public string Descripcion { get; set; }
        public long Id_Paquete { get; set; }
        public long Id_Bodega { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Paquete Paquete { get; set; }
    }
}
