//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageDelivery.Repository.Implementation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public long Id { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public string Descripcion { get; set; }
        public long Id_Paquete { get; set; }
        public long Id_Bodega { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Paquete Paquete { get; set; }
    }
}
