//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageDelivery.Repository.Implementation.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PackageDeliveryEntities : DbContext
    {
        public PackageDeliveryEntities()
            : base("name=PackageDeliveryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Envio> Envio { get; set; }
        public virtual DbSet<EstadoEnvio> EstadoEnvio { get; set; }
        public virtual DbSet<Historial> Historial { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Oficina> Oficina { get; set; }
        public virtual DbSet<Paquete> Paquete { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoTransporte> TipoTransporte { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
