//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Person_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Person_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
  
    ViewBag.Title = "Create";


#line default
#line hidden

#line 3 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
using (Html.BeginForm()) 
{
    

#line default
#line hidden

#line 4 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
                            
    


#line default
#line hidden

#line 6 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
__o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.LabelFor(model => model.OtherNames, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.EditorFor(model => model.OtherNames, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 12 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.OtherNames, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.LabelFor(model => model.FirstLastName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.EditorFor(model => model.FirstLastName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 15 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.FirstLastName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 16 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.LabelFor(model => model.SecondLastName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 17 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.EditorFor(model => model.SecondLastName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 18 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.SecondLastName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 19 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.LabelFor(model => model.IdentificationNumber, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 20 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.EditorFor(model => model.IdentificationNumber, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 21 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.IdentificationNumber, "", new { @class = "text-danger" });


#line default
#line hidden

#line 22 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.LabelFor(model => model.CellPhone, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 23 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.EditorFor(model => model.CellPhone, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 24 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.CellPhone, "", new { @class = "text-danger" });


#line default
#line hidden

#line 25 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 26 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 27 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" });


#line default
#line hidden

#line 28 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.LabelFor(model => model.Id_DocumentType);


#line default
#line hidden

#line 29 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.DropDownListFor(model => model.Id_DocumentType, new SelectList(Model.DocumentTypeList, "Id", "Name"), new { @class = "form-control chosen-select-single", @id = "selDocumentType", data_placeholder = "-- Seleccione el tipo de documento --" });


#line default
#line hidden

#line 30 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
   __o = Html.ValidationMessageFor(model => model.Id_DocumentType, "", new { @class = "text-danger" });


#line default
#line hidden

#line 31 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
      
}

#line default
#line hidden

#line 32 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
DefineSection("Scripts", () => {


#line 33 "C:\Users\Juan Camilo UL\AppData\Local\Temp\2E7554D122FEA7FA5ACF8AA02A67452FCBE3\3\PackageDeliverySystem\PackageDelivery.GUI\Views\Person\Create.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
